version: '2'

jobs:
  lint:
    docker:
      - image: php:alpine
    steps:
      - checkout
      - run:
          name: Install Composer
          command: |
            curl -sS https://getcomposer.org/installer | php
            mv composer.phar /usr/local/bin/composer
      - run:
          name: Composer Install
          command: composer install --no-progress --no-interaction
      - run:
          name: Composer Check Style
          command: composer check-style

  test-php56:
    docker:
      - image: php:5.6-alpine
    steps:
      - checkout
      - run:
          name: Install xDebug Extension
          command: |
            apk add --no-cache --no-progress g++ make autoconf bash
            pecl -q install xdebug-2.5.5
            docker-php-ext-enable xdebug
      - run:
          name: Install Composer
          command: |
            curl -sS https://getcomposer.org/installer | php
            mv composer.phar /usr/local/bin/composer
      - run:
          name: Composer Install
          command: composer install --no-progress --no-interaction
      - run:
          name: Composer Test
          command: composer test -- --coverage-text
      - run:
          name: Upload Code Coverage
          command: |
            curl -s https://codecov.io/bash > .codecov
            chmod +x .codecov
            ./.codecov
      - store_artifacts:
          path: build/coverage
          destination: coverage

  test-php70:
    docker:
      - image: php:7.0-alpine
    steps:
      - checkout
      - run:
          name: Install Composer
          command: |
            curl -sS https://getcomposer.org/installer | php
            mv composer.phar /usr/local/bin/composer
      - run:
          name: Composer Install
          command: composer install --no-progress --no-interaction
      - run:
          name: Composer Test
          command: composer test

  test-php71:
    docker:
      - image: php:7.1-alpine
    steps:
      - checkout
      - run:
          name: Install Composer
          command: |
            curl -sS https://getcomposer.org/installer | php
            mv composer.phar /usr/local/bin/composer
      - run:
          name: Composer Install
          command: composer install --no-progress --no-interaction
      - run:
          name: Composer Test
          command: composer test -- --coverage-text

  test-php72:
    docker:
      - image: php:7.2-alpine
    steps:
      - checkout
      - run:
          name: Install Composer
          command: |
            curl -sS https://getcomposer.org/installer | php
            mv composer.phar /usr/local/bin/composer
      - run:
          name: Composer Install
          command: composer install --no-progress --no-interaction
      - run:
          name: Composer Test
          command: composer test

workflows:
  version: 2
  tests:
    jobs:
      - lint
      - test-php56
      - test-php70
      - test-php71
      - test-php72
